### ISSUE TITLE
Use Remote Docker Host

### ISSUE THREAD

**Issue by RAbraham** [mutagen-io/mutagen-compose#24]
Hi,
How do I run `mutagen-compose` on a remote host(called `zeus` which has a docker daemon). I may be incorrectly providing `DOCKER_HOST`. I'm trying to run the data science example in the examples folder

The following commands work
```
export ZEUS_USER=rajiv
ssh zeus
docker -H "ssh://$ZEUS_USER@zeus" run -v "/home/$ZEUS_USER/livesync/$PROJECT_NAME:/$PROJECT_NAME" -v "/:/host" -w "/$PROJECT_NAME"
```
Outside this docker experiment, I was able to successfully use `mutagen sync`. So mutagen works.

The following commands didn't work:
```shell
export DOCKER_HOST=ssh://rajiv@zeus && mutagen-compose up
# or 
mutagen-compose -H "ssh://rajiv@zeus" up

```

The error I get is:

```
[+] Running 6/6
 ⠿ mutagen Pulled                                                                     3.0s
   ⠿ df9b9388f04a Pull complete                                                       1.3s
   ⠿ c619346dabd9 Pull complete                                                       1.4s
   ⠿ 65c51f140dce Pull complete                                                       1.5s
   ⠿ 8f47ad349b1a Pull complete                                                       1.7s
   ⠿ ca4590cc6e67 Pull complete                                                       1.9s
[+] Running 2/4
 ⠿ Network data-science_default      Created                                          0.1s
 ⠿ Volume "data-science_code"        Created                                          0.0s
 ⠿ Container data-science-mutagen-1  Starting                                         0.9s
 ⠿ Mutagen                           Error: unable to create forwarding ...           0.1s
unable to bring up Mutagen Compose sidecar service: unable to reconcile Mutagen sessions: unable to create forwarding session (jupyter): unable to connect to destination: unable to connect to endpoint: unable to dial agent endpoint: unable to create agent command: unable to probe container: container probing failed under POSIX hypothesis (exit status 1) and Windows hypothesis (exit status 1)

```

Details:
- Mutagen
```
❯ mutagen-compose version
Mutagen version 0.14.0
Compose version v2.5.1
Docker version v20.10.12

```

UPDATE:
I noticed that a container was created remotely during this process. But I'm not sure if that was the only container required.
```
# Remote Machine Zeus
rajiv@Zeus:~$ docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS          PORTS                                                                                          NAMES
f86abf45b1e3   mutagenio/sidecar:0.14.0-enhanced   "mutagen-sidecar"        15 minutes ago   Up 15 minutes                                                                                                  data-science-mutagen-1
```

Thanks for making this project!

**Comment by xenoscopic** [comment]
@RAbraham There's been trouble in the past with the Docker SSH transport (that I still need to look into, it seems).  I think it has to do with not properly supporting half-closure of streams (which becomes problematic with non-interactive usage of `docker exec`), but it seems to be a little different in every case.  Unfortunately it's a little outside Mutagen's control.

The more reliable way is typically to create a standalone Mutagen forwarding session to forward a local Unix domain socket to `/var/run/docker.sock` on the remote host, e.g.

```
mutagen forward create unix:~/.docker.sock rajiv@zeus:unix:/var/run/docker.sock
```

and then use something like `DOCKER_HOST=unix:///$HOME/.docker.sock` (or create a Docker context to target that local socket).  Since Mutagen's forwarding does support half-closure of streams, this will typically be more reliable, but let me know if it's still giving you trouble.

**Comment by RAbraham** [comment]
`DOCKER_HOST`worked. I'll try to work with that before trying out Docker Contexts.

There is a typo though. one less slash `DOCKER_HOST=unix://$HOME/.docker.sock`

Thanks!

**Comment by xenoscopic** [comment]
> There is a typo though. one less slash `DOCKER_HOST=unix://$HOME/.docker.sock`

D'oh!  Thanks for the corrected version.

I'll make a point to look into the issue with Docker's built-in SSH transport for Mutagen v0.15.
