### ISSUE TITLE
 container probing failed

### ISSUE THREAD

**Issue by numito** [mutagen-io/mutagen-compose#4]
Error: unable to reconcile Mutagen sessions: unable to create synchronization session (app): unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to create agent command: unable to probe container: container probing failed under POSIX hypothesis (exit status 1) and Windows hypothesis (exit status 1)

System: macOS 11.6
Mutagen: version 0.13.0-beta2
Docker: version 20.10.10
Docker Compose: version v2.1.1
Use Docker Compose V2 is checked and active

When I do a mutage compose up, the following happens:
Volumes are created, then mutagen sidecar is started and then I get this error. Other containers are not started.

**Comment by numito** [comment]
Sorry used wrong command ! mutagen-compose works. 
It would be good to autostart mutagen with mutagen-compose.

Thank you!

**Comment by xenoscopic** [comment]
Thanks for the report!

Sorry about the autostart - it should work but it's a bug.  Now tracked in #5.

**Comment by cdimartino** [comment]
> Sorry used wrong command ! mutagen-compose works. It would be good to autostart mutagen with mutagen-compose.
> 
> Thank you!

Can you provide more detail on what the _"correct command"_ should be? Hitting the same issue.

**Comment by Craeckerffm** [comment]
mutagen-compose up
you might want to restart the daemon

**Comment by xenoscopic** [comment]
@cdimartino You'll want to use the separate `mutagen-compose` command (which is the Compose V2-based Mutagen integration provided by this repo) rather than the built-in `mutagen compose` command, which is Compose V1-based and slated for removal upon the final release of Mutagen v0.13.
