### ISSUE TITLE
PHPStorm complains that 

### ISSUE THREAD

**Issue by rawroland** [mutagen-io/mutagen-compose#60]
## Kudos

Thank you for the great tool ❤️!

## Summary

Cannot execute mutagen-compose in phpstorm but functional on the command line.

### Mutagen
```
Mutagen version 0.17.0
Compose version v2.15.1
Docker version v20.10.20
Docker Desktop 4.19.0 (106363)
Use Docker Compose V2 enabled
```

### Platforms
```
PhpStorm 2023.1
Build #PS-231.8109.199, built on March 29, 2023
MacBook Pro
Ventura 13.3.1
```

## Details
When trying to change the Docker tools in phpstorm to use `mutagen-compose`, I get the error `/usr/local/bin/mutagen-compose is not a valid docker-compose executable`. This makes it impossible to use mutagen-compose in phpstorm, e.g. for running tests in the IDE. I am not sure if this a mutagen-compose issue or a phpstorm issue.

## Image
![Bildschirmfoto 2023-05-02 um 12 16 37](https://user-images.githubusercontent.com/557246/235640793-38a3060c-246a-4eb6-bf5b-be4af3ac51f7.png)

**Comment by michalkleiner** [comment]
This is most likely not an issue with mutagen-compose itself, PhpStorm will just be picky about the binary/executable name is my guess. Try to rename the original docker-compose binary to something else and then symlink or rename `mutagen-compose` to `docker-compose` and try again with the 'faux' docker-compose.

**Comment by rawroland** [comment]
@michalkleiner Thanks for your quick feedback. I noticed after saving the form with the error that it does function correctly. The error was therefore misleading. I would consider this issue as done.
