### ISSUE TITLE
Restart policy for Mutagen Sidecar

### ISSUE THREAD

**Issue by yeslad** [mutagen-io/mutagen-compose#8]
Hi Mutagen Team!

We've been using Mutagen + Mutagen Compose version 0.13.0-beta3 on macOS and it has been working well.

One thing that would be great addition for us would be to include the option to set a [restart policy](https://docs.docker.com/config/containers/start-containers-automatically/) for the Mutgen Sidecar container.
In can be a bit frustrating trying to figure out why the sync is not working, until you realize that when you installed that latest Docker update (for example) and restarted, all of your own containers are running due to their configured restart policies, while the Mutgen Sidecar container is not!

Thanks!

**Comment by xenoscopic** [comment]
This is a good point.  I'll have a look at this tomorrow, should be a trivial fix.  I'm thinking that maybe `unless-stopped` would be the correct policy for the sidecar (just to avoid surprises that might arise with `always`).

What are your thoughts on the correct policy?

**Comment by yeslad** [comment]
Thanks for responding so quickly!
`unless-stopped` sounds like a reasonable default, though if it could be configurable as an `x-mutagen` attribute that would probably be most useful.

**Comment by xenoscopic** [comment]
That makes sense.  I would propose adding a `sidecar` key under `x-mutagen` that accepts a limited subset of the Compose Spec service configuration, for now, just:

```
x-mutagen:
    sidecar:
        restart: "<restart-policy-name>"
```

The default behavior would be `unless-stopped`.  I'll code that up real quick and see how it looks.

**Comment by xenoscopic** [comment]
I've just pushed a commit that enables this functionality (though I haven't done any testing yet).  I'll play around with this and tag/release it tomorrow.

In the meantime, you can test it out by doing a `git clone` followed by `go run scripts/build.go` (in which case you'll find a `mutagen-compose` binary in the `build` directory).

**Comment by xenoscopic** [comment]
Okay, I've tagged v0.13.0-beta3-2 with the ability to change the sidecar restart policy, but I've decided to leave the default behavior the same as it was (unspecified).  I think it's too significant of a change for the default case and most users don't use a non-default restart policy with Compose services anyway.

So you can set the sidecar service restart policy with something like:

```
x-mutagen:
  sidecar:
    restart: "unless-stopped"
```

(adjusting the policy to your preference).

**Comment by yeslad** [comment]
This is great, thanks!
